name: Run Unittests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.5.0
        with:
          compiler: ${{ matrix.dc }}

      - name: Install gdb
        run: sudo apt-get install gdb

      - name: Install meson
        run: pip3 install meson

      - name: Test meson with DMD
        run: meson build && meson test --verbose -C build
        if: ${{ matrix.dc == 'dmd-latest' }}

      - name: Test meson with LDC
        run: DFLAGS="-link-defaultlib-shared" meson build && meson test --verbose -C build
        if: ${{ matrix.dc == 'ldc-latest' }}

      - name: Run dub tests
        run: |
          dub test -b unittest-cov corectl
          dub test -b unittest-cov corehelper
          dub test -b unittest-cov corecollector

      - name: Upload Codecoverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
