name: Run Unittests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install D compiler
        uses: mihails-strasuns/setup-dlang@v0.3.1
        with:
          compiler: ${{ matrix.dc }}

      - name: Install meson
        run: pip3 install meson

      - name: Test meson build
        run: meson build && ninja -C build

      - name: Run dub tests
        run: dub test corecollector
